### ISSUE TITLE
UndoManager#forgetHistory should invalidate undoAvailable, redoAvailable, etc.

### ISSUE THREAD

**Issue by ryanjaeb** [FXMisc/UndoFX#1]
If forgetHistory discards all previous history, should it invalidate the undoAvailable and redoAvailable properties?  Also, should it automatically update the marked position to ensure it isn't pointing to some old, forgotten position?

**Comment by benedictleejh** [comment]
Sorry to bump an old issue, but if I need to clear the redo, how should I do it then? Since forgetHistory doesn't affect redo.

**Comment by TomasMikula** [comment]
Hmm, well, I didn't think of that. What is the use case for it?

**Comment by benedictleejh** [comment]
On creating a new document, changes in the redo queue should not be able to be applied to the new document, but as it is currently, you can, with the caveat of potentially strange behaviour depending on the program.

**Comment by TomasMikula** [comment]
What about creating a new UndoManager for the new document?

**Comment by benedictleejh** [comment]
Hmm, I tried that, but while the actual queue is cleared, bindings to `redoAvailableProperty` aren't, so on a UI level, that shows up and could be confusing.

**Comment by TomasMikula** [comment]
Well, you need to rebind it to the new UndoManager's `redoAvailableProperty`. You might want to use `flatMap` so that you don't have to rebind "manually":

```java
class Document {
    UndoManager getUndoManager();
}

Val<Document> currentDocumentProperty = ...;
Val<Boolean> redoAvailable = currentDocumentProperty.flatMap(doc -> doc.getUndoManager().redoAvailableProperty());
redoButton.disableProperty().bind(redoAvailable.map(x -> !x));
```

Now as you change the `Document` in `currentDocumentProperty`, the `redoButton` will automatically switch to its UndoManager's `redoAvailableProperty`.

**Comment by benedictleejh** [comment]
Hmm, I'll need to meditate on that for a while. My application currently uses a global undo manager, and I expose `undoAvailableProperty` and `redoAvailableProperty` as

```scala
def undoAvailable: ObservableBooleanValue = undoManager.undoAvailableProperty()
def redoAvailable: ObservableBooleanValue = undoManager.redoAvailableProperty()
```

and fire events using their `onChange` methods (from ScalaFX)

```scala
 UndoController.undoAvailable onChange { (_, _, available) =>
    EventBus.send(UndoStatus(available, UndoEventSourceIdentity))
  }
  UndoController.redoAvailable onChange { (_, _, available) =>
    EventBus.send(RedoStatus(available, UndoEventSourceIdentity))
  }
```

What you're describing could work, but I need to figure out how to make it work in context.

**Comment by TomasMikula** [comment]
Just replace the global UndoManager with one that comes with the document. It doesn't really have to be part of the document; you can have e.g. a DocumentWrapper that holds a document and an UndoManager and then have a `Property<DocumentWrapper>`. Then `flatMap` that to define `redoAvailable`, `undoAvailable`.

**Comment by benedictleejh** [comment]
Ok, after meditating over it for a while, how I did it in the end was to wrap the UndoManager inside an ObjectProperty and using EasyBind to `flatMap` the ObjectProperty to expose the required properties.

**Comment by TomasMikula** [comment]
:+1:
